#!/usr/bin/env python3
"""Generate a big synthetic design for benchmarking lfc.

The module is a bank of independent datapath blocks (ALUs, min/max units,
hash mixers, MACs, counters) with the kind of waste real RTL has: constant
mode selects, masks that cancel out, logic nobody reads. Block sizes vary on
purpose so the thread pool has uneven work to balance.

    python3 tools/gen_bench.py --blocks 2000 --seed 1 > bench.sv
"""
import argparse
import random


def alu(i, w):
    return f"""
  // block {i}: alu
  logic [{w-1}:0] x{i}, z{i}, t{i}, u{i};
  assign x{i} = a[{w*i+w-1}:{w*i}];
  assign z{i} = b[{w*i+w-1}:{w*i}];
  assign t{i} = (x{i} + z{i}) ^ ((x{i} & {w}'h{'F0'*(w//8)}) | (x{i} & {w}'h{'0F'*(w//8)}));
  assign u{i} = sel[{i}] ? t{i} - z{i} : (MODE == 1 ? x{i} * z{i} : t{i});
  assign y[{w*i+w-1}:{w*i}] = u{i} ^ (x{i} & ~x{i});
  assign flag[{i}] = ^u{i} | (&x{i});
"""


def minmax(i, w):
    return f"""
  // block {i}: min/max
  logic [{w-1}:0] x{i}, z{i}, lo{i}, hi{i};
  assign x{i} = a[{w*i+w-1}:{w*i}];
  assign z{i} = b[{w*i+w-1}:{w*i}];
  assign lo{i} = (x{i} < z{i}) ? x{i} : z{i};
  assign hi{i} = (x{i} < z{i}) ? z{i} : x{i};
  assign y[{w*i+w-1}:{w*i}] = sel[{i}] ? hi{i} - lo{i} : lo{i};
  assign flag[{i}] = (hi{i} == lo{i});
"""


def mixer(i, w):
    return f"""
  // block {i}: hash mixer
  logic [{w-1}:0] x{i}, z{i}, h{i}, dead{i};
  assign x{i} = a[{w*i+w-1}:{w*i}];
  assign z{i} = b[{w*i+w-1}:{w*i}];
  assign h{i} = x{i} ^ (x{i} << 1) ^ (z{i} >> 2) ^ {{x{i}[{w//2-1}:0], z{i}[{w-1}:{w//2}]}};
  assign dead{i} = h{i} * z{i};
  assign y[{w*i+w-1}:{w*i}] = sel[{i}] ? h{i} : ~(~h{i});
  assign flag[{i}] = ^{{x{i}, z{i}, h{i}}};
"""


def mac(i, w):
    h = w // 2
    return f"""
  // block {i}: multiply-accumulate
  logic [{w-1}:0] x{i}, z{i}, p{i}, q{i};
  assign x{i} = a[{w*i+w-1}:{w*i}];
  assign z{i} = b[{w*i+w-1}:{w*i}];
  assign p{i} = x{i}[{h-1}:0] * z{i}[{h-1}:0] + x{i}[{w-1}:{h}];
  assign q{i} = x{i}[{w-1}:{h}] + z{i}[{h-1}:0] * x{i}[{h-1}:0];
  assign y[{w*i+w-1}:{w*i}] = sel[{i}] ? p{i} : q{i};
  assign flag[{i}] = (p{i} != q{i});
"""


def counter(i, w):
    return f"""
  // block {i}: counter
  logic [{w-1}:0] x{i}, c{i};
  assign x{i} = a[{w*i+w-1}:{w*i}];
  always_ff @(posedge clk) begin
    if (rst) c{i} <= {w}'d0;
    else if (sel[{i}]) c{i} <= x{i};
    else c{i} <= c{i} + {w}'d1;
  end
  assign y[{w*i+w-1}:{w*i}] = c{i} ^ b[{w*i+w-1}:{w*i}];
  assign flag[{i}] = (c{i} == x{i});
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--blocks", type=int, default=2000)
    ap.add_argument("--seed", type=int, default=1)
    ap.add_argument("--width", type=int, default=8, help="bits per block lane")
    args = ap.parse_args()
    rnd = random.Random(args.seed)
    n, w = args.blocks, args.width
    kinds = [alu, minmax, mixer, mac, counter]
    out = [f"// generated by tools/gen_bench.py --blocks {n} --seed {args.seed} --width {w}",
           "module bench #(parameter MODE = 0) (",
           "  input  logic clk,",
           "  input  logic rst,",
           f"  input  logic [{n*w-1}:0] a,",
           f"  input  logic [{n*w-1}:0] b,",
           f"  input  logic [{n-1}:0] sel,",
           f"  output logic [{n*w-1}:0] y,",
           f"  output logic [{n-1}:0] flag",
           ");"]
    for i in range(n):
        out.append(rnd.choice(kinds)(i, w))
    out.append("endmodule")
    print("\n".join(out))


if __name__ == "__main__":
    main()
