#include "writer.h"

#include <map>
#include <sstream>

namespace lf {

namespace {

std::string range(const NetDecl& d) {
  if (!d.vector) return "";
  return "[" + std::to_string(d.msb) + ":" + std::to_string(d.lsb) + "] ";
}

// Names of sources (input bits by port, flop outputs by register), indexed by
// node id. Gates are printed as _n<id>. Used to be a std::map lookup per fanin,
// which made writing the netlist slower than optimizing it.
struct Names {
  std::vector<std::string> src;
  std::map<std::string, bool> vec;

  Names(const Graph& g) : src(g.size()) {
    for (const auto& d : g.nets) vec[d.name] = d.vector;
    for (const auto& b : g.inputs) src[b.node] = vec[b.name] ? b.name + "[" + std::to_string(b.bit) + "]" : b.name;
    for (const auto& f : g.flops)
      src[f.q] = vec[f.name] ? f.name + "__q[" + std::to_string(f.bit) + "]" : f.name + "__q";
  }

  void put(std::string& out, uint32_t x) const {
    if (x == kFalse) out += "1'b0";
    else if (x == kTrue) out += "1'b1";
    else if (!src[x].empty()) out += src[x];
    else {
      out += "_n";
      out += std::to_string(x);
    }
  }

  std::string operator()(uint32_t x) const {
    std::string s;
    put(s, x);
    return s;
  }
};

}  // namespace

std::string write_verilog(const Graph& g) {
  Qor q = measure(g);
  Names nm(g);
  std::string os;
  os.reserve(g.size() * 28 + 1024);
  os += "// generated by lfc: " + std::to_string(q.gates) + " gates, depth " + std::to_string(q.depth) + ", " +
        std::to_string(q.flops) + " flops\n";
  os += "module " + g.module + " (\n";
  bool first = true;
  for (const auto& d : g.nets) {
    if (d.kind == NetKind::Reg) continue;
    os += first ? "  " : ",\n  ";
    os += d.kind == NetKind::Input ? "input " : "output ";
    os += range(d) + d.name;
    first = false;
  }
  os += "\n);\n";

  for (const auto& d : g.nets) {
    if (d.kind != NetKind::Reg) continue;
    bool used = false;
    for (const auto& f : g.flops) used |= f.name == d.name;
    if (used) os += "  reg " + range(d) + d.name + "__q;\n";
  }

  static const char* sym[] = {"", "", "", "", "~", " & ", " | ", " ^ ", " ? "};
  for (uint32_t i = 2; i < g.size(); i++) {
    const Node& n = g.nodes[i];
    if (!is_gate(n.op)) continue;
    os += "  wire _n";
    os += std::to_string(i);
    os += " = ";
    if (n.op == Op::Not) {
      os += "~";
      nm.put(os, n.in[0]);
    } else {
      nm.put(os, n.in[0]);
      os += sym[int(n.op)];
      nm.put(os, n.in[1]);
      if (n.op == Op::Mux) {
        os += " : ";
        nm.put(os, n.in[2]);
      }
    }
    os += ";\n";
  }

  for (const auto& o : g.outputs) {
    os += "  assign " + o.name;
    if (nm.vec.at(o.name)) os += "[" + std::to_string(o.bit) + "]";
    os += " = ";
    nm.put(os, o.node);
    os += ";\n";
  }

  std::map<std::string, std::vector<const Flop*>> by_clock;
  for (const auto& f : g.flops) by_clock[f.clock].push_back(&f);
  for (const auto& [clk, fl] : by_clock) {
    os += "  always @(posedge " + clk + ") begin\n";
    for (const Flop* f : fl) {
      os += "    ";
      nm.put(os, f->q);
      os += " <= ";
      nm.put(os, f->d);
      os += ";\n";
    }
    os += "  end\n";
  }
  os += "endmodule\n";
  return os;
}

std::string write_dot(const Graph& g) {
  Names nm(g);
  std::ostringstream os;
  os << "digraph \"" << g.module << "\" {\n  rankdir=LR;\n  node [fontname=\"Helvetica\"];\n";
  std::vector<char> used(g.size(), 0);
  for (uint32_t i = 2; i < g.size(); i++)
    for (int j = 0; j < op_arity(g.nodes[i].op); j++) used[g.nodes[i].in[j]] = 1;
  for (const auto& o : g.outputs) used[o.node] = 1;
  for (const auto& f : g.flops) used[f.d] = 1;
  for (uint32_t i = 0; i < g.size(); i++) {
    const Node& n = g.nodes[i];
    if (i < 2 && !used[i]) continue;
    if (is_source(n.op))
      os << "  n" << i << " [shape=box, label=\"" << nm(i) << "\"];\n";
    else
      os << "  n" << i << " [shape=ellipse, label=\"" << op_name(n.op) << "\"];\n";
    for (int j = 0; j < op_arity(n.op); j++) {
      os << "  n" << n.in[j] << " -> n" << i;
      if (n.op == Op::Mux) os << " [label=\"" << (j == 0 ? "s" : j == 1 ? "1" : "0") << "\"]";
      os << ";\n";
    }
  }
  for (const auto& o : g.outputs) {
    std::string id = "out_" + o.name + "_" + std::to_string(o.bit);
    os << "  " << id << " [shape=box, style=bold, label=\"" << o.name << "[" << o.bit << "]\"];\n";
    os << "  n" << o.node << " -> " << id << ";\n";
  }
  for (const auto& f : g.flops) os << "  n" << f.d << " -> n" << f.q << " [style=dashed, label=\"D\"];\n";
  os << "}\n";
  return os.str();
}

}  // namespace lf
